/*
Synonimy - inne nazwy obiektów
*/
--synonimy prywatne
CREATE SYNONYM pracownicy FOR employees; 
select * from pracownicy;
DROP SYNONYM pracownicy;
select * from pracownicy;

GRANT SELECT ON employees TO sql100;
CREATE SYNONYM pracownicy FOR sql100.employees; 

--synonimy dostêpne dla wszystkich u¿ytkowników - publiczne
CREATE PUBLIC SYNONYM products FOR sql100.employees; --nie mam takich uprawnieñ, ale prosze mi wierzyæ, to dzia³a

/*Sekwencje
generuj¹ sekwencje liczb ca³kowitych. S¹ zazwyczaj u¿ywane do generowania wartoœci do klucza g³ównego

CREATE SEQUENCE nazwa_sekwencji
START WITH
INCEREMENT WITH
[MAXVALUE]
[MINVALUE]
*/
CREATE SEQUENCE seq_1; --start with 1, increment with 1
CREATE SEQUENCE seq_2
START WITH 100
INCREMENT BY -2
MINVALUE 10
MAXVALUE 100;

select seq_2.nextval from dual;
select seq2.currval, seq_2.nextval from dual;

--u¿ycie sekwencji w tabeli
CREATE SEQUENCE s_default_value_for_column;
CREATE TABLE test_with_sequence(
    id INTEGER CONSTRAINT test_with_sequence_pk PRIMARY KEY,
    sequence_value INTEGER DEFAULT s_default_value_for_column.NEXTVAL
)
INSERT INTO test_with_sequence (id) VALUES (1);
INSERT INTO test_with_sequence (id) VALUES (2);
INSERT INTO test_with_sequence (id) VALUES (3);
INSERT INTO test_with_sequence (id) VALUES (4);

select * from test_with_sequence;



--u¿ycie sekwencji natywnie w create table
CREATE TABLE test_with_identity (
    id INTEGER CONSTRAINT test_with_identity_pk PRIMARY KEY,
    identity_value INTEGER GENERATED BY DEFAULT AS IDENTITY (
        START WITH 5 INCREMENT BY 2
    )
);
INSERT INTO test_with_identity (id) VALUES (1);
INSERT INTO test_with_identity (id) VALUES (2);
INSERT INTO test_with_identity (id) VALUES (3);
INSERT INTO test_with_identity (id) VALUES (4);

select * from test_with_identity